In [2]:
import numpy as np

Creating Arrays - One Dimensional

In [5]:
print(np.zeros(5))
print(np.ones(5))
# Create an array of a specified shape with a specific value - np.full(shape, value)
print(np.full(5, 2.5))
# Create a range of evely spaced values - np.arange(size), np.arange(start, stop, step)
print(np.arange(10))
print(np.arange(2,10,2)) # Result would be 2,4,6,8. The last jump would be on 10, which will get ignored
# Another way to create an array with evenly spaced values - np.linspace(start, stop, number of spaces - 1)
print(np.linspace(2,10,11))
# Create an array from a list
arr = np.array([1,2,4,6,7,8])
print(arr)

# Access the element and change
print(arr[2])
print(arr[3:])
print(arr[2:5]) # Elements at indices 2, 3, 4
print(arr[2::2]) # Elements at indices 2 and 4 - the last jump would be on the last position which will get ignored

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[2.5 2.5 2.5 2.5 2.5]
[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]
[ 2.   2.8  3.6  4.4  5.2  6.   6.8  7.6  8.4  9.2 10. ]
[1 2 4 6 7 8]
4
[6 7 8]
[4 6 7]
[4 7]


Create Array - Multi-Dimensional

In [11]:
print(np.ones((5,2))) # A matrix of 5x2 shape
print(np.zeros((2,3,4))) # Two 3x4 matrices
# Create an array using a list (or list of lists and so on)
arr = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ])
print(arr)

# Access the element and change
arr[0,2] = 30
print(arr[:,2]) # Access the second-indexed column
print(arr[0,:]) # Access the zero-indexed row
arr[:,1] = [1, 10, 100] # Change the values of first-indexed column
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[30  6  9]
[ 1  2 30]
[[  1   1  30]
 [  4  10   6]
 [  7 100   9]]


Randomly Generated Arrays

In [16]:
# Set the seed of the pseudo-random number generator to make results reproducible
np.random.seed(1000)
# Generate numbers from a uniform distribution
print(np.random.rand(5,2)) # Random array of shape 5x2
# Generate numbers from a normal distribution
print(np.random.randn(5,2))
# Generate an array of random integers
print(np.random.randint(low=1,high=100,size=(2,5,2))) # High is excluded

[[0.65358959 0.11500694]
 [0.95028286 0.4821914 ]
 [0.87247454 0.21233268]
 [0.04070962 0.39719446]
 [0.2331322  0.84174072]]
[[ 0.66728131 -0.80611561]
 [-1.19606983 -0.40596016]
 [-0.18237734  0.10319289]
 [-0.13842199  0.70569237]
 [ 1.27179528 -0.98674733]]
[[[33 53]
  [51 22]
  [27  8]
  [17 88]
  [93 44]]

 [[60  1]
  [32 31]
  [19  2]
  [12 47]
  [28 48]]]


Element-wise Operations

In [32]:
# Perform one or more element-wise add/sub/mul/div/mod/exp/log to each element of an array
arr1 = 1 + np.arange(5)
print(arr1)
arr2 = 10 + 2*np.arange(5)**2
print(arr2)
# Element-wise operations between two arrays
print((arr1 + arr2) + 10); print(arr1 * arr2)
print(arr1 > 2) # Compare each element with 2
print(arr1 > arr2/10) # Element-wise comparison of the array values
print(arr1[arr1 > arr2/10]) # Output the values at TRUE indices


[1 2 3 4 5]
[10 12 18 28 42]
[21 24 31 42 57]
[ 10  24  54 112 210]
[False False  True  True  True]
[False  True  True  True  True]
[2 3 4 5]


Summarizing Operations

In [38]:
# One dimensional array
print(arr1)
print(arr1.min()); print(arr1.max()); print(arr1.sum()); print(arr1.mean()); print(arr1.std())
# Multi dimensional array
np.random.seed(2000)
arr3 = np.random.randint(low=10,high=50,size=(2,2,5))
print(arr3)
print(arr3.min()); print(arr3.max()); print(arr3.sum()); print(arr3.mean()); print(arr3.std())

[1 2 3 4 5]
1
5
15
3.0
1.4142135623730951
[[[18 24 23 46 38]
  [38 24 46 25 37]]

 [[12 11 22 40 33]
  [49 35 38 42 43]]]
11
49
644
32.2
11.187493016757596
