In [1]:
import numpy as np

Element-wise Operations

In [2]:
# Multiply a vector by a scalar
u = np.array([2,4,5,6])
print(2*u)

# Add two vectors
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])
print(u+v)

[ 4  8 10 12]
[3 4 5 8]


Vector - Vector Multiplication

In [3]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])
print(np.dot(u,v))
print(sum(u*v))

# Code from scratch - sum(u*v)
def vector_vector_multiplication(u, v):
    assert(u.shape == v.shape) # To ensure we have same shaped-vectors
    result = 0
    for i in range(u.shape[0]):
        result += u[i] * v[i]
    return result

vector_vector_multiplication(u, v)

14
14


np.int64(14)

Matrix - Vector Multiplication

In [4]:
U = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
v = np.array([1,0.5,2,1])

print([sum(i*v) for i in U])
print([np.dot(i,v) for i in U])
print(np.dot(U,v))

def matrix_vector_multiplication(U, v):
    assert(U.shape[1] == v.shape[0])

    num_rows = U.shape[0]
    result = np.empty(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

matrix_vector_multiplication(U, v)

[np.float64(20.0), np.float64(6.0), np.float64(8.5)]
[np.float64(20.0), np.float64(6.0), np.float64(8.5)]
[20.   6.   8.5]


array([20. ,  6. ,  8.5])

Matrix - Matrix Multiplication

In [15]:
U = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
V = np.array([[1,1,2],[0,0.5,1],[0,2,1],[2,1,0]])

print(np.dot(U,V))

def matrix_matrix_multiplication(U, V):
    assert(U.shape[1] == V.shape[0])

    n_rows = U.shape[0]
    n_cols = V.shape[1]

    result = np.empty((n_rows, n_cols))

    for i in range(n_cols):
        Uvi = matrix_vector_multiplication(U, V[:,i])
        result[:,i] = Uvi
    return result

matrix_matrix_multiplication(U,V)

[[14.  20.  13. ]
 [ 5.   6.   5. ]
 [ 5.   8.5  9. ]]


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

Identity Matrix - U.I = U and I.U = U

In [22]:
identity = np.eye(3)
custom_identity = np.eye(V.shape[1], V.shape[0])

print(V)
print(np.dot(V,identity))
print(custom_identity) # The last column of the custom identity is all zeros
print(np.dot(V,custom_identity)) # The new matrix is no longer the same matrix as the original once - hence the dimensions of matrix and identity matrix need to be the same

[[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]
 [2.  1.  0. ]]
[[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]
 [2.  1.  0. ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1.  1.  2.  0. ]
 [0.  0.5 1.  0. ]
 [0.  2.  1.  0. ]
 [2.  1.  0.  0. ]]


Inverse of a Matrix

In [30]:
# The matrix for which an inverse needs to be calculated should be a square matrix
V = np.random.rand(3,3)
V_inverse = np.linalg.inv(V)
print(np.dot(V,V_inverse)) # An identity matrix - we can get extremely small values not equal to zero due to floating point precision errors

[[ 1.00000000e+00  7.89516815e-17 -4.31337092e-17]
 [ 7.97829944e-17  1.00000000e+00  8.49287643e-17]
 [-2.71277407e-17 -7.18600203e-18  1.00000000e+00]]
